// Complete list of Croydon Tramlink stations with NaptanIds
const TRAM_STATIONS = [
  { id: "940GZZCRADD", name: "Addiscombe" },
  { id: "940GZZCRADV", name: "Addington Village" },
  { id: "940GZZCRAMP", name: "Ampere Way" },
  { id: "940GZZCRARA", name: "Arena" },
  { id: "940GZZCRAVE", name: "Avenue Road" },
  { id: "940GZZCRBED", name: "Beddington Lane" },
  { id: "940GZZCRBEK", name: "Beckenham Junction" },
  { id: "940GZZCRBGV", name: "Belgrave Walk" },
  { id: "940GZZCRBIR", name: "Birkbeck" },
  { id: "940GZZCRBLA", name: "Blackhorse Lane" },
  { id: "940GZZCRBRD", name: "Beckenham Road" },
  { id: "940GZZCRCEN", name: "George Street" },
  { id: "940GZZCRCHR", name: "Church Street" },
  { id: "940GZZCRCOO", name: "Coombe Lane" },
  { id: "940GZZCRCTR", name: "Centrale" },
  { id: "940GZZCRDDR", name: "Dundonald Road" },
  { id: "940GZZCRECR", name: "East Croydon" },
  { id: "940GZZCRELM", name: "Elmers End" },
  { id: "940GZZCRFLD", name: "Fieldway" },
  { id: "940GZZCRGRP", name: "Gravel Hill" },
  { id: "940GZZCRHRD", name: "Harrington Road" },
  { id: "940GZZCRKGR", name: "King Henry's Drive" },
  { id: "940GZZCRLBN", name: "Lebanon Road" },
  { id: "940GZZCRLOY", name: "Lloyd Park" },
  { id: "940GZZCRMDN", name: "Merton Park" },
  { id: "940GZZCRMJT", name: "Mitcham Junction" },
  { id: "940GZZCRMIT", name: "Mitcham" },
  { id: "940GZZCRNWA", name: "New Addington" },
  { id: "940GZZCRPHI", name: "Phipps Bridge" },
  { id: "940GZZCRREE", name: "Reeves Corner" },
  { id: "940GZZCRSAN", name: "Sandilands" },
  { id: "940GZZCRSHE", name: "Therapia Lane" },
  { id: "940GZZCRSTD", name: "Staddon Road" },  
  { id: "940GZZCRWAD", name: "Waddon Marsh" },
  { id: "940GZZCRWCR", name: "West Croydon" },
  { id: "940GZZCRWEL", name: "Wellesley Road" },
  { id: "940GZZCRWMB", name: "Wimbledon" },
  { id: "940GZZCRWOD", name: "Woodside" },
];

export default TRAM_STATIONS;